import type { Request, Response, NextFunction } from 'express';
import * as youtubeService from '../services/youtube.service.js';
import * as geminiService from '../services/gemini.service.js';
import type { SupportedLanguage } from '../services/gemini.service.js';
import { ValidationError } from '../middleware/error.middleware.js';

/**
 * YouTube 비디오 ID 추출
 */
function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /^([a-zA-Z0-9_-]{11})$/,
  ];

  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match?.[1]) return match[1];
  }
  return null;
}

/**
 * POST /api/youtube/summarize
 * YouTube URL에서 자막 추출 후 요약
 */
export async function summarizeYoutube(req: Request, res: Response, next: NextFunction) {
  try {
    const { url, language = 'korean' } = req.body;

    if (!url) {
      throw new ValidationError('YouTube URL is required');
    }

    const videoId = extractVideoId(url);
    if (!videoId) {
      throw new ValidationError('Invalid YouTube URL');
    }

    const lang: SupportedLanguage = language.includes('en') ? 'en' : 'ko';

    console.log(`Summarizing YouTube video: ${videoId}, language: ${lang}`);

    // 1. 자막 추출 시도
    let transcript: string;
    let transcriptSource = 'captions';

    try {
      const captionResult = await youtubeService.getTranscript(videoId);
      transcript = captionResult.text;
      console.log(`Captions found (${captionResult.language}, auto: ${captionResult.isAutoGenerated})`);
    } catch (captionError) {
      // 자막 없으면 오디오 다운로드 시도
      console.log('No captions available, trying audio download...');

      try {
        const audioResult = await youtubeService.downloadAudio(videoId);
        transcript = await geminiService.transcribeAudioBuffer(
          audioResult.buffer,
          audioResult.mimeType
        );
        transcriptSource = 'audio';
        console.log('Transcribed from audio');
      } catch (audioError) {
        const message = audioError instanceof Error ? audioError.message : 'Unknown error';
        if (message === 'YT_DLP_NOT_INSTALLED') {
          throw new ValidationError('이 영상에는 자막이 없고, 오디오 다운로드 도구(yt-dlp)가 설치되어 있지 않습니다.');
        }
        throw new ValidationError(`자막 및 오디오 처리 실패: ${message}`);
      }
    }

    // 2. 요약 생성
    const result = await geminiService.summarizeFromTranscript(
      transcript,
      `YouTube Video (${videoId})`,
      lang
    );

    res.json({
      data: {
        summary: result.summary,
        transcript: result.transcript,
        title: result.suggestedTitle,
        videoId,
        transcriptSource,
      },
    });
  } catch (error) {
    next(error);
  }
}
